FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# copy only csproj first (for caching)
COPY AssetForge.API.csproj ./
RUN dotnet restore

# copy everything else
COPY . ./
RUN dotnet publish -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .

ENV ASPNETCORE_URLS=http://+:10000
EXPOSE 10000

ENTRYPOINT ["dotnet", "AssetForge.API.dll"]